chain_width = 60
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
max_width = 120
reorder_imports = true
struct_lit_single_line = false
use_field_init_shorthand = true
wrap_comments = true
