[package]
edition = "2021"
name = "wenfox-cli"
version = "0.1.0"

[dependencies]
chrono = {workspace = true}
clap = {workspace = true}
colored = {workspace = true}
lazy_static = {workspace = true}
log = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
serde_yaml = {workspace = true}
toml = {workspace = true}

[[bin]]
name = "wenfox-cli"
path = "src/main.rs"
